# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=400, verbose_name='Url')),
                ('year', models.IntegerField(blank=True, verbose_name='Год')),
                ('price', models.CharField(blank=True, max_length=400, verbose_name='Цена')),
                ('currency_type', models.CharField(blank=True, max_length=400, verbose_name='Валюта')),
                ('run', models.CharField(blank=True, max_length=400, verbose_name='Пробег')),
                ('run_metric', models.CharField(blank=True, max_length=400, verbose_name='Еденица пробега')),
                ('horse_power', models.IntegerField(blank=True, verbose_name='Лошадинные силы')),
                ('color', models.CharField(blank=True, max_length=400, verbose_name='Цвет')),
                ('body_type', models.CharField(blank=True, max_length=400, verbose_name='Тип кузова')),
                ('engine_type', models.CharField(blank=True, max_length=400, verbose_name='Тип двигателя')),
                ('gear_type', models.CharField(blank=True, max_length=400, verbose_name='Привод')),
                ('transmission', models.CharField(blank=True, max_length=400, verbose_name='Трансмисия')),
                ('steering_wheel', models.CharField(blank=True, max_length=400, verbose_name='Руль')),
                ('displacement', models.CharField(blank=True, max_length=400, verbose_name='Объем двигателя')),
                ('stock', models.CharField(blank=True, max_length=400, verbose_name='Статус')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Изображение')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='updater.Auto')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Наиминование')),
                ('image', models.ImageField(blank=True, default='', max_length=300, upload_to='', verbose_name='Логотип марки')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наиминование')),
                ('image', models.ImageField(blank=True, default='', max_length=300, upload_to='', verbose_name='Изображение модели')),
                ('mark', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='updater.Mark', verbose_name='Марка')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(blank=True, max_length=500, null=True, verbose_name='Диллерский центр')),
                ('phone', models.CharField(blank=True, max_length=400, null=True, verbose_name='Телефон')),
                ('adress', models.CharField(blank=True, max_length=400, null=True, verbose_name='Адресс')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seller/', verbose_name='Изображение')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='updater.City', verbose_name='Город')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='model',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='updater.Model', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='auto',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='updater.Seller', verbose_name='Диллерский центр'),
        ),
    ]
